### ISSUE TITLE
Import ERROR: desres

### ISSUE THREAD

**Issue by parashardhapola** [DEShawResearch/SIMPLEchangepoint#1]
I get following error on running 'build-all.sh'

ImportError: No module named desres:
  File "/home/satish/SIMPLEchangepoint/SIMPLEchangepoint/MDanalysis_package/src/molfile-1.10.15/SConstruct", line 1:
    import desres

**Comment by lusimon81** [comment]
I get the same error.

does someone know how to solve it?

Thanks

**Comment by alanianeselli** [comment]
Me too, i get the exact same error. Have you been able to solve the problem?
Thanks

**Comment by majia67** [comment]
I have successfully installed this package on my workstation before (though quite difficult to do so). I think this is a bug because the 'desres' package is not included in the prerequisites of the package installation (it actually doesn't). This bug happens when the script tries to test the 'molfile' installation which relies on the 'desres' package. There're two ways to solve this problem:

1. Install any D.E.Shaw research software that could install the 'desres' package for you (like DESMOND, http://www.deshawresearch.com/resources_desmond.html).
2.  Comment the testing code of 'molfile' package in the 'build-all.sh' file.

By the way, I suggest to communicate with the author through email. It seems like he seldom check the github issues.

Thanks and hope this information could help.

**Comment by carendle** [comment]
The problem arises because of a bug in the 'build-all.sh' script that assumed that the PYTHONPATH environment variable is predefined in the user's shell environment.  We recently pushed a change to the repository that fixes that issue.
